version: '3'
services:
  nginx:
    image: nexus.solarsecurity.ru/nginx:1.23
    container_name: front
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80
    links:
      - node

  node:
    build:
      dockerfile: Dockerfile.node
      context: .
    image: node-back
    container_name: back
    environment:
      - "BRANCH=${BRANCH}"
    working_dir: /app
    volumes:
      - ./index.js:/app/index.js
      - 'back:/app/data'

volumes:
  back:


